# default configuration
baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "CIBCCA"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about"
name = "Corporación"
weight = 1

[[menu.main]]
URL = "blog"
name = "Noticias"
weight = 2

[[menu.main]]
URL = "portfolio"
name = "Historia"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contacto"
weight = 4


# default parameters
[params]
home = "Inicio"
logo = ""
# theme color
theme_color = "#333895"
# contact info
phone = "+xxx xxx xxxx"
email = "jose.roco@cibcca.cl"
address = "Ingresar Dirección"
# meta description
author = "José Luis Roco Contreras"
description = "Corporación para la Integración del Borde Costero Central de Arica"
# google analytics
google_analytics_id = "G-NY5J92LSDS" # Your ID
# copyright
copyright = "Copyright &copy; 2020 CIBCCA"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = true
form_action = "https://formspree.io/f/xknpzyko" # contact form works with : https://formspree.io

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyDcYmkpfUJlz82RUknm_QR07ZBtmATaViE&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "-18.47235901296731"
map_longitude = "-70.31649703700374"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
# [[params.social]]
# icon = "ti-facebook"
# URL = "#"

# [[params.social]]
# icon = "ti-instagram"
# URL = "#"

# [[params.social]]
# icon = "ti-dribbble"
# URL = "#"

# [[params.social]]
# icon = "ti-twitter-alt"
# URL = "#"